/**
 * UNIVERSAL TEMPLATE REGISTRY
 * Metadata for all universal templates
 */

interface UniversalTemplateMetadata {
  id: string
  name: string
  description: string
  category: 'minimal' | 'modern' | 'creative' | 'classic' | 'executive' | 'academic'
  tags: string[]
  author: string
  features: string[]
  bestFor: string[]
  popularity?: number
}

export const UNIVERSAL_TEMPLATE_REGISTRY: UniversalTemplateMetadata[] = [
  {
    id: 'atlantic_blue',
    name: 'Atlantic Blue',
    description: 'Professional design with dark sidebar and photo',
    category: 'modern',
    tags: ['sidebar', 'photo', 'modern', 'professional', 'blue'],
    author: 'CV-Helper',
    features: [
      'Dark left sidebar with photo',
      'Visual skill indicators',
      'Clean white content area',
      'Sidebar certifications',
    ],
    bestFor: [
      'Creative professionals',
      'Tech workers',
      'Modern industries',
      'Candidates with photo',
    ],
    popularity: 95,
  },
  {
    id: 'executive',
    name: 'Executive',
    description: 'Traditional two-column formal layout with serif typography',
    category: 'executive',
    tags: ['traditional', 'serif', 'two-column', 'formal', 'executive'],
    author: 'CV-Helper',
    features: [
      'Centered header with contact',
      'Two-column layout',
      'Serif typography',
      'Professional formatting',
    ],
    bestFor: [
      'Senior executives',
      'Management positions',
      'Traditional industries',
      'Formal contexts',
    ],
    popularity: 92,
  },
  {
    id: 'mercury',
    name: 'Mercury',
    description: 'Clean centered design with photo and modern aesthetic',
    category: 'modern',
    tags: ['centered', 'photo', 'modern', 'clean', 'minimal'],
    author: 'CV-Helper',
    features: [
      'Centered photo at top',
      'Skills as tags',
      'Clean modern aesthetic',
      'Visual language indicators',
    ],
    bestFor: [
      'Young professionals',
      'Creative roles',
      'Modern companies',
      'Visual portfolios',
    ],
    popularity: 90,
  },
  {
    id: 'classic',
    name: 'Classic',
    description: 'Traditional right-aligned header with timeless design',
    category: 'classic',
    tags: ['traditional', 'serif', 'right-aligned', 'classic', 'professional'],
    author: 'CV-Helper',
    features: [
      'Right-aligned contact info',
      'Traditional serif font',
      'Clean sectioning',
      'ATS-friendly',
    ],
    bestFor: [
      'All industries',
      'Conservative fields',
      'ATS systems',
      'Traditional companies',
    ],
    popularity: 88,
  },
  {
    id: 'harvard',
    name: 'Harvard',
    description: 'Minimal academic design with education-first approach',
    category: 'academic',
    tags: ['academic', 'minimal', 'education-first', 'research', 'simple'],
    author: 'CV-Helper',
    features: ['Education listed first', 'Categorized skills', 'Research-friendly', 'Minimal clean design'],
    bestFor: [
      'Students',
      'Recent graduates',
      'Academic positions',
      'Research roles',
    ],
    popularity: 85,
  },
  {
    id: 'evergreen',
    name: 'Evergreen',
    description: 'Two-column layout with dark header and skill progress bars',
    category: 'modern',
    tags: ['modern', 'two-column', 'progress-bars', 'photo', 'professional'],
    author: 'CV-Helper',
    features: ['Dark teal header', 'Skill progress bars', 'Two-column layout', 'Photo integrated'],
    bestFor: [
      'Tech professionals',
      'AEM Developers',
      'Experienced candidates',
      'Skill-heavy roles',
    ],
    popularity: 88,
  },
  {
    id: 'youngcurve',
    name: 'YoungCurve',
    description: 'Academic CV with burgundy accents and numbered publications',
    category: 'academic',
    tags: ['academic', 'research', 'publications', 'photo', 'clean'],
    author: 'CV-Helper',
    features: ['Burgundy square markers', 'Numbered publications', 'Photo in header', 'Research-focused'],
    bestFor: [
      'PhD candidates',
      'Researchers',
      'Academics',
      'Publication-heavy CVs',
    ],
    popularity: 82,
  },
  {
    id: 'simple_hipster',
    name: 'Simple Hipster',
    description: 'Two-column layout with green sidebar, photo, and skill progress bars',
    category: 'modern',
    tags: ['modern', 'sidebar', 'photo', 'skill-bars', 'two-column', 'green'],
    author: 'LaTeX Ninja (converted from Overleaf)',
    features: [
      'Green sidebar with photo',
      'Skill progress bars',
      'Timeline-style experience',
      'Comprehensive sections (publications, certs)',
    ],
    bestFor: [
      'Tech professionals',
      'Creative developers',
      'Modern industries',
      'Skill-focused roles',
    ],
    popularity: 87,
  },
  {
    id: 'simple_hipster_proper',
    name: 'Simple Hipster CV',
    description: 'Professional two-column layout with dark header, cyan accents, and timeline experience',
    category: 'modern',
    tags: ['modern', 'sidebar', 'photo', 'timeline', 'two-column', 'cyan', 'professional'],
    author: 'LaTeX Ninja (Overleaf)',
    features: [
      'Dark gray header bar',
      'Cyan accent badges',
      'Orange gradient skill bars',
      'Timeline-style experience with dots',
      'Language proficiency dots',
      'Circular photo in sidebar',
    ],
    bestFor: [
      'Creative professionals',
      'Tech industry',
      'Modern companies',
      'Portfolio-focused roles',
    ],
    popularity: 92,
  },
  {
    id: 'jack_sparrow',
    name: 'Jack Sparrow CV',
    description: 'Two-column layout with dark header, cyan badges, and orange skill bars',
    category: 'modern',
    tags: ['modern', 'sidebar', 'photo', 'skill-bars', 'two-column', 'cyan', 'orange'],
    author: 'LaTeX Overleaf (Converted)',
    features: [
      'Dark gray header (65px)',
      'Cyan accent badges',
      'Horizontal orange gradient skill bars',
      'Timeline-style experience',
      'Compact sidebar (27%)',
      'Publications and awards sections',
    ],
    bestFor: [
      'Creative professionals',
      'Tech industry',
      'Modern companies',
      'Skill-focused roles',
    ],
    popularity: 90,
  },
  {
    id: 'creative_cv',
    name: 'Creative CV',
    description: 'Two-column layout with photo in header, pie chart, and red/burgundy theme',
    category: 'creative',
    tags: ['creative', 'photo-header', 'pie-chart', 'two-column', 'red', 'burgundy', 'unique'],
    author: 'LaTeX Overleaf (Converted)',
    features: [
      'Photo in header (top right)',
      'Pie chart for "A Day of My Life"',
      'Red/burgundy accent color',
      'Language proficiency dots',
      'Tag cloud for strengths',
      'Icon badges for achievements',
      'Timeline-style experience',
    ],
    bestFor: [
      'Creative professionals',
      'Designers',
      'Unique personalities',
      'Portfolio-focused roles',
    ],
    popularity: 88,
  },
  {
    id: 'academic_cv',
    name: 'Academic CV',
    description: 'Single-column traditional academic layout with serif font',
    category: 'academic',
    tags: ['academic', 'traditional', 'serif', 'single-column', 'publications', 'research'],
    author: 'LaTeX Academic (Converted)',
    features: [
      'Centered header with contact',
      'Traditional serif typography',
      'Publications section',
      'Awards & Honors',
      'Clean section dividers',
      'ATS-friendly format',
    ],
    bestFor: [
      'Academics',
      'Researchers',
      'PhD candidates',
      'Faculty positions',
      'Research roles',
    ],
    popularity: 85,
  },
  {
    id: 'cv9',
    name: 'CV9 - Modern Professional',
    description: 'Green icon with initials, gray/white two-column layout',
    category: 'modern',
    tags: ['modern', 'two-column', 'icon', 'professional', 'green', 'gray'],
    author: 'LiveCareer (Converted)',
    features: [
      'Green square icon with initials',
      'Diagonal X pattern',
      'Gray left column with white sections',
      'Contact bar below header',
      'Professional Summary in sidebar',
      'Clean modern aesthetic',
    ],
    bestFor: [
      'Modern professionals',
      'Corporate roles',
      'Project managers',
      'Consultants',
    ],
    popularity: 87,
  },
  {
    id: 'cv1',
    name: 'CV1 - Orange Sidebar',
    description: 'Orange sidebar with photo and white main content',
    category: 'modern',
    tags: ['modern', 'sidebar', 'photo', 'orange', 'two-column', 'bold'],
    author: 'LiveCareer (Converted)',
    features: [
      'Orange sidebar (30%)',
      'Photo with orange border',
      'Contact in sidebar',
      'Professional Summary in sidebar',
      'Core Qualifications',
      'Bold orange accents',
    ],
    bestFor: [
      'Creative professionals',
      'Sales roles',
      'Marketing positions',
      'Retail management',
    ],
    popularity: 89,
  },
  {
    id: 'cv12',
    name: 'CV12 - Red Top Bar',
    description: 'Red top bar with white/gray two-column layout',
    category: 'modern',
    tags: ['modern', 'two-column', 'red', 'photo', 'sidebar', 'professional'],
    author: 'LiveCareer (Converted)',
    features: [
      'Red top bar accent',
      'Circular photo in sidebar',
      'Pink background sections',
      'White left + Gray right columns',
      'Contact in sidebar',
      'Core Qualifications',
    ],
    bestFor: [
      'Sales professionals',
      'Retail workers',
      'Customer service',
      'Modern industries',
    ],
    popularity: 86,
  },
  {
    id: 'modern_resume',
    name: 'Modern Resume - Yellow/Navy',
    description: 'Yellow/gold sidebar with circular photo and navy bottom section',
    category: 'modern',
    tags: ['modern', 'sidebar', 'photo', 'yellow', 'navy', 'creative', 'bold'],
    author: 'ResumeSector (Converted)',
    features: [
      'Yellow/gold sidebar (23%)',
      'Circular photo with yellow ring',
      'Navy bottom section in sidebar',
      'Yellow circular section icons',
      'Skill progress bars',
      'White content cards on gray',
      'Yellow timeline bullets',
    ],
    bestFor: [
      'Creative professionals',
      'Graphic designers',
      'Modern industries',
      'Tech professionals',
      'Marketing roles',
    ],
    popularity: 91,
  },
  {
    id: 'ivy_league',
    name: 'Ivy League',
    description: 'Professional single-column layout with blue accents and achievement grid',
    category: 'classic',
    tags: ['professional', 'single-column', 'blue', 'clean', 'ats-friendly', 'achievements'],
    author: 'Enhancv (Converted)',
    features: [
      'Centered header with contact info',
      'Navy blue section headers',
      'Achievement grid (3 columns)',
      'Light blue company names',
      'Clean serif headings (Volkhov)',
      'Professional sans-serif body (PT Sans)',
      'ATS-friendly format',
    ],
    bestFor: [
      'Finance professionals',
      'Consultants',
      'Corporate roles',
      'Traditional industries',
      'Executive positions',
      'ATS systems',
    ],
    popularity: 93,
  },
  {
    id: 'stockholm',
    name: 'Stockholm',
    description: 'Clean minimalist single-column layout with green/teal accents',
    category: 'modern',
    tags: ['minimalist', 'single-column', 'green', 'clean', 'ats-friendly', 'modern'],
    author: 'Enhancv (Converted)',
    features: [
      'Bold serif name header',
      'Green/teal accent color',
      'Full-width section underlines',
      'Icon-based contact info',
      'Clean minimalist spacing',
      'Professional typography',
      'ATS-friendly format',
    ],
    bestFor: [
      'Tech professionals',
      'Modern industries',
      'Minimalist aesthetic',
      'Corporate roles',
      'Clean design preference',
      'ATS systems',
    ],
    popularity: 92,
  },
  {
    id: 'double-column',
    name: 'Double Column',
    description: 'Extracted from Enhancv - Double Column template with professional design',
    category: 'modern',
    tags: ["enhancv","professional","clean","multi-column"],
    author: 'Enhancv (Converted)',
    features: [
      'Clean professional design',
      'ATS-friendly format',
      'Color-coded sections',
      'Modern typography',
    ],
    bestFor: [
      'Professional roles',
      'Modern industries',
      'Clean aesthetic',
    ],
    popularity: 88,
  },
  {
    id: 'creative-orange',
    name: 'Creative Orange',
    description: 'Creative CV with orange wave header, teal accents, and two-column layout',
    category: 'creative',
    tags: ['creative', 'orange', 'teal', 'two-column', 'photo', 'waves', 'modern'],
    author: 'Custom Design',
    features: [
      'Orange gradient wave header',
      'Circular profile photo with teal border',
      'Teal and orange accent colors',
      'Progress bars for skills',
      'Icon-based sections',
      'Two-column layout',
      'Decorative wave footer',
    ],
    bestFor: [
      'Creative professionals',
      'Designers',
      'Modern industries',
      'Portfolio-focused roles',
      'Unique personalities',
    ],
    popularity: 89,
  },
  {
    id: 'teal-modern',
    name: 'Teal Modern',
    description: 'Modern CV with teal header, gray sidebar, and checkmark sections',
    category: 'modern',
    tags: ['modern', 'teal', 'gray', 'sidebar', 'checkmarks', 'clean', 'professional'],
    author: 'Custom Design',
    features: [
      'Teal gradient header',
      'Pricing/badge display',
      'Circular profile photo',
      'Gray rounded sidebar',
      'Checkmark section indicators',
      'Icon-based contact info',
      'Clean modern layout',
    ],
    bestFor: [
      'Modern professionals',
      'Consultants',
      'Service providers',
      'Freelancers',
      'Tech industry',
    ],
    popularity: 87,
  },
  {
    id: 'beige-sidebar',
    name: 'Beige Sidebar',
    description: 'Professional CV with beige sidebar, hexagonal logo, and justified text',
    category: 'classic',
    tags: ['classic', 'beige', 'sidebar', 'professional', 'clean', 'elegant', 'hexagon'],
    author: 'CodePen by mavrK',
    features: [
      'Gray header bar',
      'Beige sidebar (#F7E0C1)',
      'Hexagonal logo with initials',
      'Social media links',
      'Justified text layout',
      'Clean section separators',
      'Professional typography',
    ],
    bestFor: [
      'Corporate professionals',
      'Executives',
      'Traditional industries',
      'Consultants',
      'Business roles',
    ],
    popularity: 90,
  },
  {
    id: 'dark-blue-orange',
    name: 'Dark Blue Orange',
    description: 'Modern CV with dark blue background, orange accents, and skill progress bars',
    category: 'modern',
    tags: ['modern', 'dark', 'blue', 'orange', 'skills', 'progress-bars', 'creative'],
    author: 'CodePen Design',
    features: [
      'Dark blue background (#1a237e)',
      'Orange accent color (#ffb300)',
      'Skill progress bars',
      'Circular social icons',
      'Timeline-style experience',
      'Skewed profile section',
      'Icon-based sections',
    ],
    bestFor: [
      'Web designers',
      'Frontend developers',
      'Creative professionals',
      'Tech industry',
      'Modern roles',
    ],
    popularity: 92,
  },
  {
    id: 'gray-minimal',
    name: 'Gray Minimal',
    description: 'Clean and minimal CV with gray sidebar and professional layout',
    category: 'minimal',
    tags: ['minimal', 'gray', 'clean', 'professional', 'sidebar', 'modern'],
    author: 'Professional Design',
    features: [
      'Gray sidebar (#b8b8b8)',
      'White main content area',
      'Expandable sections with + icons',
      'Circular profile photo',
      'Clean typography',
      'Bullet point lists',
      'Contact icons',
    ],
    bestFor: [
      'Content creators',
      'Marketing professionals',
      'Corporate roles',
      'Professional services',
      'Clean aesthetic preference',
    ],
    popularity: 88,
  },
  {
    id: 'dark-professional',
    name: 'Dark Professional',
    description: 'Modern dark CV with geometric patterns, green accents, and timeline layout',
    category: 'modern',
    tags: ['dark', 'modern', 'green', 'geometric', 'timeline', 'professional'],
    author: 'Modern Design',
    features: [
      'Dark teal gradient background',
      'Geometric pattern overlay',
      'Green accent color (#4ade80)',
      'Icon-based experience timeline',
      'Skill progress bars',
      'Rounded profile photo',
      'Contact info with icons',
    ],
    bestFor: [
      'Software engineers',
      'Web developers',
      'Tech professionals',
      'Modern industries',
      'Creative tech roles',
    ],
    popularity: 91,
  },
  {
    id: 'orange-sidebar',
    name: 'Orange Sidebar',
    description: 'Modern two-column CV with dark sidebar and horizontal orange contact section',
    category: 'modern',
    tags: ['modern', 'orange', 'two-column', 'sidebar', 'clean', 'professional'],
    author: 'Modern Design',
    features: [
      'Dark sidebar (#2d2d2d)',
      'Orange contact section (#ff6347)',
      'Two-column layout',
      'Profile photo area',
      'Horizontal contact section',
      'Skills with orange bullets',
      'Contact icons with circles',
    ],
    bestFor: [
      'UI/UX designers',
      'Graphic designers',
      'Creative professionals',
      'Modern industries',
      'Portfolio-focused roles',
    ],
    popularity: 89,
  },
  {
    id: 'teal-rounded',
    name: 'Teal Rounded',
    description: 'Modern CV with dark teal background, circular profile photo, and rounded white sections',
    category: 'modern',
    tags: ['modern', 'teal', 'rounded', 'cards', 'dark', 'clean'],
    author: 'Modern Design',
    features: [
      'Dark teal gradient background',
      'Circular profile photo with border',
      'Rounded white card sections',
      'Skill progress bars',
      'Two-column layout',
      'Contact icons with circles',
      'Box shadows for depth',
    ],
    bestFor: [
      'Graphic designers',
      'Creative professionals',
      'Modern industries',
      'Digital designers',
      'Portfolio roles',
    ],
    popularity: 90,
  },
  {
    id: 'navy-professional',
    name: 'Navy Professional',
    description: 'Professional CV with navy blue sidebar and white main content area',
    category: 'classic',
    tags: ['classic', 'navy', 'blue', 'professional', 'sidebar', 'clean'],
    author: 'Professional Design',
    features: [
      'Navy blue sidebar (#1e3a5f)',
      'White main content area',
      'Profile photo section',
      'Bullet points for entries',
      'Navy section headers',
      'Clean typography',
      'Two-column layout',
    ],
    bestFor: [
      'Communication professionals',
      'Corporate roles',
      'Traditional industries',
      'Business professionals',
      'Executive positions',
    ],
    popularity: 87,
  },
  {
    id: 'blue-circular',
    name: 'Blue Circular',
    description: 'Modern French CV with dark blue sidebar, circular profile photo, and timeline layout',
    category: 'modern',
    tags: ['modern', 'blue', 'circular', 'timeline', 'french', 'clean'],
    author: 'Modern Design',
    features: [
      'Dark blue sidebar (#1e3d5c)',
      'Circular profile photo with curved background',
      'Timeline layout with dots',
      'Language progress bars',
      'Light gray main content (#d0d4d8)',
      'French section names',
      'Two-column layout',
    ],
    bestFor: [
      'Project managers',
      'French professionals',
      'Modern industries',
      'Creative roles',
      'European market',
    ],
    popularity: 89,
  }
]

/**
 * Get template metadata by ID
 */
export function getUniversalTemplateById(id: string): UniversalTemplateMetadata | undefined {
  return UNIVERSAL_TEMPLATE_REGISTRY.find(t => t.id === id)
}

/**
 * Get all visible templates
 */
export function getUniversalTemplates(): UniversalTemplateMetadata[] {
  return UNIVERSAL_TEMPLATE_REGISTRY
}

/**
 * Get templates by category
 */
export function getUniversalTemplatesByCategory(
  category: UniversalTemplateMetadata['category']
): UniversalTemplateMetadata[] {
  return UNIVERSAL_TEMPLATE_REGISTRY.filter(t => t.category === category)
}

/**
 * Search templates by query
 */
export function searchUniversalTemplates(query: string): UniversalTemplateMetadata[] {
  const lowerQuery = query.toLowerCase()
  return UNIVERSAL_TEMPLATE_REGISTRY.filter(
    t =>
      t.name.toLowerCase().includes(lowerQuery) ||
      t.description.toLowerCase().includes(lowerQuery) ||
      t.tags.some(tag => tag.toLowerCase().includes(lowerQuery)) ||
      t.bestFor.some(use => use.toLowerCase().includes(lowerQuery))
  )
}
