/**
 * REACT TEMPLATES - MAIN EXPORT FILE
 * Central export point for all React templates and utilities
 */

// Export all template components
export {
  AtlanticBlue,
  Executive,
  Harvard,
  Evergreen,
  YoungCurve,
  TealModernTemplate,
  DarkBlueOrangeTemplate,
  OrangeSidebarTemplate,
  TealRoundedTemplate,
  NavyProfessionalTemplate,
  BlueCircularTemplate,
  CreativeCVTemplate,
  AcademicCVTemplate,
  ModernProfessionalTemplate,
  OrangeAccentTemplate,
  RedTopBarTemplate,
  ModernResumeYellowTemplate,
  GeometricCoralTemplate,
  AcademicBurgundyTemplate,
  Template31,
  Template32,
  Template33,
  Template34,
  Template35,
  Template37,
  Template38,
  Template39,
  Template40,
  Template41,
  Template42,
  Template43,
  Template44,
  ProductManagerTemplate,
  AtlanticBlueFieldEditable as AtlanticBlueEditable,
  ExecutiveFieldEditable as ExecutiveEditable,
  HarvardFieldEditable as HarvardEditable,
  EvergreenFieldEditable as EvergreenEditable,
  YoungCurveFieldEditable as YoungCurveEditable,
  CreativeCVFieldEditable as CreativeCVEditable,
  AcademicCVFieldEditable as AcademicCVEditable,
  ModernProfessionalFieldEditable as ModernProfessionalEditable,
  OrangeAccentFieldEditable as OrangeAccentEditable,
  RedTopBarFieldEditable as RedTopBarEditable,
  ModernResumeYellowFieldEditable as ModernResumeYellowEditable,
  StockholmFieldEditable as StockholmEditable,
  TealModernFieldEditable as TealModernEditable,
  OrangeSidebarFieldEditable as OrangeSidebarEditable,
  TealRoundedFieldEditable as TealRoundedEditable,
  NavyProfessionalFieldEditable as NavyProfessionalEditable,
  BlueCircularFieldEditable as BlueCircularEditable,
  GeometricCoralFieldEditable as GeometricCoralEditable,
  AcademicBurgundyFieldEditable as AcademicBurgundyEditable,
  Template31FieldEditable as Template31Editable,
  Template32FieldEditable as Template32Editable,
  Template33FieldEditable as Template33Editable,
  Template34FieldEditable as Template34Editable,
  Template35FieldEditable as Template35Editable,
  Template36FieldEditable as Template36Editable,
  Template37FieldEditable as Template37Editable,
  Template38FieldEditable as Template38Editable,
  Template39FieldEditable as Template39Editable,
  Template40FieldEditable as Template40Editable,
  Template41FieldEditable as Template41Editable,
  Template42FieldEditable as Template42Editable,
  Template43FieldEditable as Template43Editable,
  Template44FieldEditable as Template44Editable,
  ProductManagerFieldEditable as ProductManagerEditable,
} from './universal-templates'

// Export types and schemas
export type {
  UniversalTemplateProps,
  UniversalResumeData,
  PersonalInfo,
  SocialLink,
  Summary,
  Experience,
  Education,
  Project,
  Skill,
  SkillCategory,
  Certification,
  Language,
  Publication,
  Award,
  Volunteer,
  Interest,
  Reference,
} from './universal-schema'

// Export registry and utilities
// Universal registry functions removed - use lib/template-registry.ts instead

// Export sample data for testing
export { COMPLETE_SAMPLE_DATA } from './sample-data-universal'
