/**
 * UNIVERSAL TEMPLATES INDEX
 * Exports all universal templates for easy import
 */

export { AtlanticBlue } from './template-1-atlantic-blue'
export { Executive } from './template-2-executive'
//export { Mercury } from './template-3-mercury'
//export { ClassicTemplate } from './template-4-classic'
export { Harvard } from './template-5-harvard'
export { Evergreen } from './template-6-evergreen'
export { YoungCurve } from './template-7-youngcurve'
//export { DoubleColumnTemplate } from './template-8-double-column'
//export { CreativeOrangeTemplate } from './template-9-creative-orange'
export { TealModernTemplate } from './template-10-teal-modern'
//export { BeigeSidebarTemplate } from './template-11-beige-sidebar'
export { DarkBlueOrangeTemplate } from './template-12-dark-blue-orange'
//export { GrayMinimalTemplate } from './template-13-gray-minimal'
//export { DarkProfessionalTemplate } from './template-14-dark-professional'
export { OrangeSidebarTemplate } from './template-15-orange-sidebar'
export { TealRoundedTemplate } from './template-16-teal-rounded'
export { NavyProfessionalTemplate } from './template-17-navy-professional'
export { BlueCircularTemplate } from './template-18-blue-circular'
//export { JackSparrowTemplate } from './template-19-jack-sparrow'
export { CreativeCVTemplate } from './template-20-creative-cv'
export { AcademicCVTemplate } from './template-21-academic'
export { ModernProfessionalTemplate } from './template-22-modern-professional'
export { OrangeAccentTemplate } from './template-23-orange-accent'
export { RedTopBarTemplate } from './template-24-red-topbar'
export { ModernResumeYellowTemplate } from './template-25-modern-resume-yellow'
//export { IvyLeagueTemplate } from './template-26-ivy-league'
//export { StockholmTemplate } from './template-27-stockholm'
export { GeometricCoralTemplate } from './template-28-geometric-coral'
//export { ModernBlueBlackTemplate } from './template-29-modern-blue-black'
export { AcademicBurgundyTemplate } from './template-30-academic-burgundy'
export { Template31 } from './template-31-lauren-chen'
export { Template32 } from './template-32-orange-sidebar-left'
export { Template33 } from './template-33-slate-yellow'
export { Template34 } from './template-34-bold-yellow'
export { Template35 } from './template-35-two-column-yellow'
//export { Template36 } from './template-36-advanced-blue'
export { Template37 } from './template-37-premium-green'
export { Template38 } from './template-38-pastel-orange'
export { Template39 } from './template-39-hybrid-green'
export { Template40 } from './template-40-professional-purple'
export { Template41 } from './template-41-unique-orange'
export { Template42 } from './template-42-aesthetic-green'
export { Template43 } from './template-43-modern-blue-hub'
export { Template44 } from './template-44-dark-yellow-split'
export { ProductManagerTemplate } from './template-31-product-manager'

// Editable versions
export { AtlanticBlueFieldEditable } from './template-1-atlantic-blue-field-editable'
export { ExecutiveFieldEditable } from './template-2-executive-field-editable'
//export { MercuryFieldEditable } from './template-3-mercury-field-editable'
//export { ClassicFieldEditable } from './template-4-classic-field-editable'
export { HarvardFieldEditable } from './template-5-harvard-field-editable'
export { EvergreenFieldEditable } from './template-6-evergreen-field-editable'
export { YoungCurveFieldEditable } from './template-7-youngcurve-field-editable'
//export { DoubleColumnFieldEditable } from './template-8-double-column-field-editable'
//export { CreativeOrangeFieldEditable } from './template-9-creative-orange-field-editable'
export { TealModernFieldEditable } from './template-10-teal-modern-field-editable'
//export { BeigeSidebarFieldEditable } from './template-11-beige-sidebar-field-editable'
//export { DarkBlueOrangeFieldEditable } from './template-12-dark-blue-orange-field-editable'
//export { GrayMinimalFieldEditable } from './template-13-gray-minimal-field-editable'
//export { DarkProfessionalFieldEditable } from './template-14-dark-professional-field-editable'
export { OrangeSidebarFieldEditable } from './template-15-orange-sidebar-field-editable'
export { TealRoundedFieldEditable } from './template-16-teal-rounded-field-editable'
export { NavyProfessionalFieldEditable } from './template-17-navy-professional-field-editable'
export { BlueCircularFieldEditable } from './template-18-blue-circular-field-editable'
//export { JackSparrowFieldEditable } from './template-19-jack-sparrow-field-editable'
export { CreativeCVFieldEditable } from './template-20-creative-cv-field-editable'
export { AcademicCVFieldEditable } from './template-21-academic-field-editable'
export { ModernProfessionalFieldEditable } from './template-22-modern-professional-field-editable'
export { OrangeAccentFieldEditable } from './template-23-orange-accent-field-editable'
export { RedTopBarFieldEditable } from './template-24-red-topbar-field-editable'
export { ModernResumeYellowFieldEditable } from './template-25-modern-resume-yellow-field-editable'
//export { IvyLeagueFieldEditable } from './template-26-ivy-league-field-editable'
export { StockholmFieldEditable } from './template-27-stockholm-field-editable'
export { GeometricCoralFieldEditable } from './template-28-geometric-coral-field-editable'
//export { ModernBlueBlackFieldEditable } from './template-29-modern-blue-black-field-editable'
export { AcademicBurgundyFieldEditable } from './template-30-academic-burgundy-field-editable'
export { Template31FieldEditable } from './template-31-lauren-chen-field-editable'
export { Template32FieldEditable } from './template-32-orange-sidebar-left-field-editable'
export { Template33FieldEditable } from './template-33-slate-yellow-field-editable'
export { Template34FieldEditable } from './template-34-bold-yellow-field-editable'
export { Template35FieldEditable } from './template-35-two-column-yellow-field-editable'
export { Template36FieldEditable } from './template-36-advanced-blue-field-editable'
export { Template37FieldEditable } from './template-37-premium-green-field-editable'
export { Template38FieldEditable } from './template-38-pastel-orange-field-editable'
export { Template39FieldEditable } from './template-39-hybrid-green-field-editable'
export { Template40FieldEditable } from './template-40-professional-purple-field-editable'
export { Template41FieldEditable } from './template-41-unique-orange-field-editable'
export { Template42FieldEditable } from './template-42-aesthetic-green-field-editable'
export { Template43FieldEditable } from './template-43-modern-blue-hub-field-editable'
export { Template44FieldEditable } from './template-44-dark-yellow-split-field-editable'
export { ProductManagerFieldEditable } from './template-31-product-manager-field-editable'

// Export types
export type { UniversalTemplateProps, UniversalResumeData } from './universal-schema'
